# 1. x vaut 5, y vaut 3, et somme contient leur somme
x = ...
y = ...
somme = ...

# 2. score vaut 100, puis on l'augmente de 15
score = ...


# 3. cellule vaut 1, puis on la multiplie par 2
cellule = ...


# 4. capital vaut 1000, puis on lui enlève 5 %
capital = ...

