# Le module math contient la fonction racine carrée et la constante pi.
# À toi de l'importer et de compléter les trois calculs.

racine_25 = ...
racine_2 = ...
pi_carre = ...

print(racine_25, racine_2, pi_carre)
